export const categoryIconImages: Record<string, string> = {
  skincare: "/images/category-icons/skincare.svg",
  haircare: "/images/category-icons/haircare.svg",
  bodycare: "/images/category-icons/bodycare.svg",
  makeup: "/images/category-icons/makeup.svg",
  perfume: "/images/category-icons/perfume.svg",
  bakhoor: "/images/category-icons/bakhoor.svg",
  baby: "/images/category-icons/baby.svg",
  supplements: "/images/category-icons/supplements.svg",
  tools: "/images/category-icons/tools.svg",
  "face-care": "/images/category-icons/face-care.svg",
  "body-care": "/images/category-icons/body-care.svg",
  cleansers: "/images/category-icons/cleansers.svg",
  toners: "/images/category-icons/toners.svg",
  serums: "/images/category-icons/serums.svg",
  moisturizers: "/images/category-icons/moisturizers.svg",
  sunscreen: "/images/category-icons/sunscreen.svg",
  "eye-care": "/images/category-icons/eye-care.svg",
  "lip-care": "/images/category-icons/lip-care.svg",
  masks: "/images/category-icons/masks.svg",
  exfoliators: "/images/category-icons/exfoliators.svg",
  shampoo: "/images/category-icons/shampoo.svg",
  conditioner: "/images/category-icons/conditioner.svg",
  "hair-oils": "/images/category-icons/hair-oils.svg",
  "body-wash": "/images/category-icons/body-wash.svg",
  "body-lotion": "/images/category-icons/body-lotion.svg",
  "body-oils": "/images/category-icons/body-oils.svg",
  "face-makeup": "/images/category-icons/face-makeup.svg",
  "eye-makeup": "/images/category-icons/eye-makeup.svg",
  "lip-makeup": "/images/category-icons/lip-makeup.svg",
  foundation: "/images/category-icons/foundation.svg",
  concealer: "/images/category-icons/concealer.svg",
  powder: "/images/category-icons/powder.svg",
  highlighter: "/images/category-icons/highlighter.svg",
  blush: "/images/category-icons/blush.svg",
  mascara: "/images/category-icons/mascara.svg",
  eyeliner: "/images/category-icons/eyeliner.svg",
  eyeshadow: "/images/category-icons/eyeshadow.svg",
  eyebrow: "/images/category-icons/eyebrow.svg",
  lipstick: "/images/category-icons/lipstick.svg",
  "lip-gloss": "/images/category-icons/lip-gloss.svg",
  "lip-oil": "/images/category-icons/lip-oil.svg",
  "perfume-women": "/images/category-icons/perfume-women.svg",
  "perfume-men": "/images/category-icons/perfume-men.svg",
  "perfume-musk": "/images/category-icons/perfume-musk.svg",
  "perfume-gift-sets": "/images/category-icons/perfume-gift-sets.svg",
  "bakhoor-premium": "/images/category-icons/bakhoor-premium.svg",
  "bakhoor-oud": "/images/category-icons/bakhoor-oud.svg",
  "bakhoor-dehn": "/images/category-icons/bakhoor-dehn.svg",
  "bakhoor-burners": "/images/category-icons/bakhoor-burners.svg",
  "baby-care": "/images/category-icons/baby-care.svg",
  vitamins: "/images/category-icons/vitamins.svg",
  "appliances-hair": "/images/category-icons/appliances-hair.svg",
  "appliances-shaving": "/images/category-icons/appliances-shaving.svg",
  "appliances-teeth": "/images/category-icons/appliances-teeth.svg",
  "tools-sub": "/images/category-icons/tools-sub.svg",
};

export function getCategoryImage(slug: string): string | null {
  return categoryIconImages[slug] || null;
}

