/**
 * Brand normalization map: raw Yaqoot brand text -> canonical Luminous brand.
 * Canonical form uses the common Arabic brand name as the storefront brand.
 * Keyed by normalized raw string. Also provides English brand + slug.
 *
 * Usage: import { normalizeBrand } from './brands.mjs'
 */

const MAP = {
  // L'Oreal group
  'لوريال': { brand: 'لوريال', brandEn: 'L’Oréal Paris', slug: 'loreal-paris' },
  'لوريال باريس': { brand: 'لوريال', brandEn: 'L’Oréal Paris', slug: 'loreal-paris' },
  'غارنييه': { brand: 'غارنييه', brandEn: 'Garnier', slug: 'garnier' },
  'غارنية': { brand: 'غارنييه', brandEn: 'Garnier', slug: 'garnier' },
  'غارنيية': { brand: 'غارنييه', brandEn: 'Garnier', slug: 'garnier' },
  'غانيه': { brand: 'غارنييه', brandEn: 'Garnier', slug: 'garnier' },
  'غانية': { brand: 'غارنييه', brandEn: 'Garnier', slug: 'garnier' },
  'ميبيلين': { brand: 'ميبلين', brandEn: 'Maybelline New York', slug: 'maybelline' },
  'ميبلين': { brand: 'ميبلين', brandEn: 'Maybelline New York', slug: 'maybelline' },
  'فيشي': { brand: 'فيشي', brandEn: 'Vichy', slug: 'vichy' },
  'لاروش بوزية': { brand: 'لاروش بوزيه', brandEn: 'La Roche-Posay', slug: 'la-roche-posay' },
  'لاروش بوزيه': { brand: 'لاروش بوزيه', brandEn: 'La Roche-Posay', slug: 'la-roche-posay' },
  'لا روش بوزاي': { brand: 'لاروش بوزيه', brandEn: 'La Roche-Posay', slug: 'la-roche-posay' },
  'يوسرين': { brand: 'يوسرين', brandEn: 'Eucerin', slug: 'eucerin' },
  'يوسيرين': { brand: 'يوسرين', brandEn: 'Eucerin', slug: 'eucerin' },
  'كيربروست': { brand: 'كيربروست', brandEn: 'Kerastase', slug: 'kerastase' },
  'جونسون': { brand: 'جونسون', brandEn: 'Johnson’s', slug: 'johnsons' },
  'جنسون': { brand: 'جونسون', brandEn: 'Johnson’s', slug: 'johnsons' },
  // La Roche group
  'انوا': { brand: 'أنوا', brandEn: 'Anew', slug: 'anew' },
  'أنوا': { brand: 'أنوا', brandEn: 'Anew', slug: 'anew' },
  // CeraVe / Cetaphil
  'سيرافي': { brand: 'سيرافي', brandEn: 'CeraVe', slug: 'cerave' },
  'سيتافيل': { brand: 'سيتافيل', brandEn: 'Cetaphil', slug: 'cetaphil' },
  'سكين 1004': { brand: 'سكين 1004', brandEn: 'SKIN1004', slug: 'skin1004' },
  'سكين1004': { brand: 'سكين 1004', brandEn: 'SKIN1004', slug: 'skin1004' },
  'سكين 100': { brand: 'سكين 1004', brandEn: 'SKIN1004', slug: 'skin1004' },
  // Bioderma
  'بايوديرما': { brand: 'بايوديرما', brandEn: 'Bioderma', slug: 'bioderma' },
  'بايو ديرما': { brand: 'بايوديرما', brandEn: 'Bioderma', slug: 'bioderma' },
  'بيوديرما': { brand: 'بايوديرما', brandEn: 'Bioderma', slug: 'bioderma' },
  'بيودانس': { brand: 'بيودانس', brandEn: 'Biodance', slug: 'biodance' },
  // Avène / Eau
  'افين': { brand: 'أفين', brandEn: 'Avène', slug: 'avene' },
  'افينو': { brand: 'أفينو', brandEn: 'Aveeno', slug: 'aveeno' },
  'افينو،': { brand: 'أفينو', brandEn: 'Aveeno', slug: 'aveeno' },
  'يورياج': { brand: 'يورياج', brandEn: 'Uriage', slug: 'uriage' },
  'سيبا ميد': { brand: 'سيباميد', brandEn: 'Sebamed', slug: 'sebamed' },
  'سيباميد': { brand: 'سيباميد', brandEn: 'Sebamed', slug: 'sebamed' },
  // Skin/Beauty Korea
  'كوسركس': { brand: 'كوسركس', brandEn: 'COSRX', slug: 'cosrx' },
  'كوكسير': { brand: 'كوسركس', brandEn: 'COSRX', slug: 'cosrx' },
  'سوم باي مي': { brand: 'سوم باي مي', brandEn: 'Some By Mi', slug: 'some-by-mi' },
  'بيوتي اوف جوسيهون': { brand: 'بيوتي أوف جوسيون', brandEn: 'Beauty of Joseon', slug: 'beauty-of-joseon' },
  'بيوتي اوف جيسهون': { brand: 'بيوتي أوف جوسيون', brandEn: 'Beauty of Joseon', slug: 'beauty-of-joseon' },
  'هارو هارو وندر': { brand: 'هارو هارو وندر', brandEn: 'Haruharu Wonder', slug: 'haruharu-wonder' },
  'ان واي اكس': { brand: 'إن واي إكس', brandEn: 'NYX', slug: 'nyx' },
  'نيكس': { brand: 'إن واي إكس', brandEn: 'NYX', slug: 'nyx' },
  'ايتود هاوس': { brand: 'ايتود هاوس', brandEn: 'Etude House', slug: 'etude-house' },
  'اتيود هاوس': { brand: 'ايتود هاوس', brandEn: 'Etude House', slug: 'etude-house' },
  'لان اورجانيك': { brand: 'لان أورجانيك', brandEn: 'Lane Organic', slug: 'lane-organic' },
  'لان اورجانك': { brand: 'لان أورجانيك', brandEn: 'Lane Organic', slug: 'lane-organic' },
  // High-end perfume
  'شانيل': { brand: 'شانيل', brandEn: 'Chanel', slug: 'chanel' },
  'شانيل للنساء': { brand: 'شانيل', brandEn: 'Chanel', slug: 'chanel' },
  'فرزاتشي': { brand: 'فرساتشي', brandEn: 'Versace', slug: 'versace' },
  'دولتشي اند جابانا': { brand: 'دولتشي آند غابانا', brandEn: 'Dolce & Gabbana', slug: 'dolce-gabbana' },
  'دولتشي آند غابانا': { brand: 'دولتشي آند غابانا', brandEn: 'Dolce & Gabbana', slug: 'dolce-gabbana' },
  'لانكوم': { brand: 'لانكوم', brandEn: 'Lancôme', slug: 'lancome' },
  'رالف لورين': { brand: 'رالف لورين', brandEn: 'Ralph Lauren', slug: 'ralph-lauren' },
  'دنهل': { brand: 'دانهيل', brandEn: 'Dunhill', slug: 'dunhill' },
  'استي لودر': { brand: 'استي لودر', brandEn: 'Estée Lauder', slug: 'estee-lauder' },
  'اريج': { brand: 'أريج', brandEn: 'Areej', slug: 'areej' },
  'اجمل': { brand: 'أجمل', brandEn: 'Ajmal', slug: 'ajmal' },
  'عساف': { brand: 'عساف', brandEn: 'Asaff', slug: 'asaff' },
  'ابراهيم القرشي': { brand: 'إبراهيم القرشي', brandEn: 'Ibrahim Al Qurashi', slug: 'ibrahim-alqurashi' },
  'عبد الصمد القرشي': { brand: 'عبد الصمد القرشي', brandEn: 'Abdul Samad Al Qurashi', slug: 'abdul-samad-alqurashi' },
  'لافيرن': { brand: 'لافيرن', brandEn: 'Laverne', slug: 'laverne' },
  'محمود سعيد': { brand: 'محمود سعيد', brandEn: 'Mahmoud Saeed', slug: 'mahmoud-saeed' },
  'الرصاصي': { brand: 'الرصاصي', brandEn: 'Al Rasasi', slug: 'al-rasasi' },
  'صنسيت كافيه': { brand: 'صنسيت كافيه', brandEn: 'Sunset Cafe', slug: 'sunset-cafe' },
  'بنش': { brand: 'بنش', brandEn: 'Bench', slug: 'bench' },
  'بينش': { brand: 'بنش', brandEn: 'Bench', slug: 'bench' },
  // Makeup brands
  'ماك': { brand: 'ماك', brandEn: 'MAC', slug: 'mac' },
  'ميك اب فور ايفر': { brand: 'ميك أب فور إيفر', brandEn: 'Make Up For Ever', slug: 'make-up-for-ever' },
  'برجوا': { brand: 'بورجوا', brandEn: 'Bourjois', slug: 'bourjois' },
  'بورجوا': { brand: 'بورجوا', brandEn: 'Bourjois', slug: 'bourjois' },
  'ريميل': { brand: 'ريميل', brandEn: 'Rimmel', slug: 'rimmel' },
  'ريميل لندن': { brand: 'ريميل', brandEn: 'Rimmel London', slug: 'rimmel' },
  'ريفلون': { brand: 'ريفيلون', brandEn: 'Revlon', slug: 'revlon' },
  'ريفلوشن': { brand: 'ريفلوشن', brandEn: 'Revolution', slug: 'revolution' },
  'ريفولوشن': { brand: 'ريفلوشن', brandEn: 'Revolution', slug: 'revolution' },
  'ريفولوشن،': { brand: 'ريفلوشن', brandEn: 'Revolution', slug: 'revolution' },
  'بنفت': { brand: 'بنفت', brandEn: 'Benefit', slug: 'benefit' },
  'تارت': { brand: 'تارت', brandEn: 'Tarte', slug: 'tarte' },
  'نيكس': { brand: 'إن واي إكس', brandEn: 'NYX', slug: 'nyx' },
  'ايسنس': { brand: 'ايسنس', brandEn: 'Essence', slug: 'essence' },
  'لوكا': { brand: 'لوكا', brandEn: 'Loca', slug: 'loca' },
  'فلورمار': { brand: 'فلورمار', brandEn: 'Flormar', slug: 'flormar' },
  'فلور مار': { brand: 'فلورمار', brandEn: 'Flormar', slug: 'flormar' },
  'ايلف': { brand: 'ايلف', brandEn: 'e.l.f.', slug: 'elf' },
  'ذا ايلف': { brand: 'ايلف', brandEn: 'e.l.f.', slug: 'elf' },
  'شيقلام': { brand: 'شيقلام', brandEn: 'Shiglam', slug: 'shiglam' },
  'سيفورا': { brand: 'سيفورا', brandEn: 'Sephora', slug: 'sephora' },
  'انجلوت': { brand: 'انجلوت', brandEn: 'Inclot', slug: 'inclot' },
  // Skincare
  'نيفيا': { brand: 'نيفيا', brandEn: 'Nivea', slug: 'nivea' },
  'دوف': { brand: 'دوف', brandEn: 'Dove', slug: 'dove' },
  'اولاي': { brand: 'أولاي', brandEn: 'Olay', slug: 'olay' },
  'فازلين': { brand: 'فازلين', brandEn: 'Vaseline', slug: 'vaseline' },
  'بالمرز': { brand: 'بالمرز', brandEn: 'Palmer’s', slug: 'palmers' },
  'بيزلين': { brand: 'بيزلين', brandEn: 'Beesline', slug: 'beesline' },
  'سانت ايفز': { brand: 'سانت آيفز', brandEn: 'St. Ives', slug: 'st-ives' },
  'سكالا': { brand: 'سكالا', brandEn: 'Scala', slug: 'scala' },
  'انيرجي': { brand: 'إنرجي', brandEn: 'Energy', slug: 'energy' },
  'وهج كير': { brand: 'وهج كير', brandEn: 'Wahaj Care', slug: 'wahaj-care' },
  'لايف بوي': { brand: 'لايف بوي', brandEn: 'Lifebuoy', slug: 'lifebuoy' },
  'فيم فريش': { brand: 'فيم فريش', brandEn: 'Femfresh', slug: 'femfresh' },
  'لوكس': { brand: 'لوكس', brandEn: 'Lux', slug: 'lux' },
  'دوف': { brand: 'دوف', brandEn: 'Dove', slug: 'dove' },
  // Hair
  'بانتين': { brand: 'بانتين', brandEn: 'Pantene', slug: 'pantene' },
  'هيربال': { brand: 'هيربال إيسنسز', brandEn: 'Herbal Essences', slug: 'herbal-essences' },
  'تريسمي': { brand: 'تريسمي', brandEn: 'TRESemmé', slug: 'tresemme' },
  'اولا هير': { brand: 'أولابلكس', brandEn: 'Olaplex', slug: 'olaplex' },
  'اولابليكس': { brand: 'أولابلكس', brandEn: 'Olaplex', slug: 'olaplex' },
  'شيسيدو': { brand: 'شيسيدو', brandEn: 'Shiseido', slug: 'shiseido' },
  'شيدا': { brand: 'شيسيدو', brandEn: 'Shiseido', slug: 'shiseido' },
  'ويلا': { brand: 'ويلا', brandEn: 'Wella', slug: 'wella' },
  'باراشوت': { brand: 'باراشوت', brandEn: 'Parachute', slug: 'parachute' },
  'دابر املا': { brand: 'دابر املا', brandEn: 'Dabur Amla', slug: 'dabur-amla' },
  'دابر': { brand: 'دابر', brandEn: 'Dabur', slug: 'dabur' },
  'موروكان اويل': { brand: 'موروكان أويل', brandEn: 'Moroccanoil', slug: 'moroccanoil' },
  'كوكو كير': { brand: 'كوكو كير', brandEn: 'Coco Care', slug: 'coco-care' },
  'انتيسا': { brand: 'انتيسا', brandEn: 'Antisa', slug: 'antisa' },
  'ريجين': { brand: 'ريجين', brandEn: 'Regen', slug: 'regen' },
  'افلون': { brand: 'أفالون', brandEn: 'Avalon', slug: 'avalon' },
  'افالون': { brand: 'أفالون', brandEn: 'Avalon', slug: 'avalon' },
  'افالون أورغانيكس': { brand: 'أفالون أورغانيكس', brandEn: 'Avalon Organics', slug: 'avalon-organics' },
  'أفالون أورغانيكس': { brand: 'أفالون أورغانيكس', brandEn: 'Avalon Organics', slug: 'avalon-organics' },
  'او جي اكس': { brand: 'أو جي إكس', brandEn: 'OGX', slug: 'ogx' },
  'هيرجرو': { brand: 'هيرجرو', brandEn: 'HairGrow', slug: 'hairgrow' },
  'سيبوري': { brand: 'سيبوري', brandEn: 'Cibori', slug: 'cibori' },
  'مويف': { brand: 'مويف', brandEn: 'Muove', slug: 'muove' },
  'اكيور': { brand: 'اكيور', brandEn: 'Acure', slug: 'acure' },
  'جولين': { brand: 'جولين', brandEn: 'Jolen', slug: 'jolen' },
  // Oral care
  'كولجيت': { brand: 'كولجيت', brandEn: 'Colgate', slug: 'colgate' },
  'كولجيت،': { brand: 'كولجيت', brandEn: 'Colgate', slug: 'colgate' },
  'كرست': { brand: 'كرست', brandEn: 'Crest', slug: 'crest' },
  'كريست': { brand: 'كرست', brandEn: 'Crest', slug: 'crest' },
  'سنسوداين': { brand: 'سنسوداين', brandEn: 'Sensodyne', slug: 'sensodyne' },
  'اورال بي': { brand: 'أورال-بي', brandEn: 'Oral-B', slug: 'oral-b' },
  'اورال بى': { brand: 'أورال-بي', brandEn: 'Oral-B', slug: 'oral-b' },
  'ليسترين': { brand: 'ليسترين', brandEn: 'Listerine', slug: 'listerine' },
  'ثيرابريث': { brand: 'ثيرابريث', brandEn: 'TheraBreath', slug: 'therabreath' },
  'بردونتكس': { brand: 'بارودونتكس', brandEn: 'Parodontax', slug: 'parodontax' },
  'بارودونتكس': { brand: 'بارودونتكس', brandEn: 'Parodontax', slug: 'parodontax' },
  'بارودونتاكس': { brand: 'بارودونتكس', brandEn: 'Parodontax', slug: 'parodontax' },
  // Supplements
  'ناو': { brand: 'ناو', brandEn: 'NOW Foods', slug: 'now-foods' },
  'ناترول': { brand: 'ناترول', brandEn: 'Natrol', slug: 'natrol' },
  'ناترول ': { brand: 'ناترول', brandEn: 'Natrol', slug: 'natrol' },
  'كاليفورنيا غولد نيوتريشن': { brand: 'كاليفورنيا غولد نيوتريشن', brandEn: 'California Gold Nutrition', slug: 'california-gold-nutrition' },
  'كاليفورنيا غولد نيوتريش': { brand: 'كاليفورنيا غولد نيوتريشن', brandEn: 'California Gold Nutrition', slug: 'california-gold-nutrition' },
  'سولغار': { brand: 'سولغار', brandEn: 'Solgar', slug: 'solgar' },
  'سنتروم': { brand: 'سنتروم', brandEn: 'Centrum', slug: 'centrum' },
  'جاميسون': { brand: 'جاميسون', brandEn: 'Jamieson', slug: 'jamieson' },
  'دكتورز بيست': { brand: 'دكتورز بيست', brandEn: 'Doctor’s Best', slug: 'doctors-best' },
  'كونتري لايف': { brand: 'كونتري لايف', brandEn: 'Country Life', slug: 'country-life' },
  'سوانسون': { brand: 'سوانسون', brandEn: 'Swanson', slug: 'swanson' },
  'سوانسون ': { brand: 'سوانسون', brandEn: 'Swanson', slug: 'swanson' },
  'فيتال بروتينز': { brand: 'فيتال بروتينز', brandEn: 'Vital Proteins', slug: 'vital-proteins' },
  'فيتابير': { brand: 'فيتابير', brandEn: 'Vitabears', slug: 'vitabears' },
  'فيتانيس ناتشرز': { brand: 'فيتانيس ناتشرز', brandEn: 'Vitanis Naturals', slug: 'vitanis-naturals' },
  'نيتشرز باونتي': { brand: 'نيتشرز باونتي', brandEn: 'Nature’s Bounty', slug: 'natures-bounty' },
  'نيتشرز واى': { brand: 'نيتشرز واي', brandEn: 'Nature’s Way', slug: 'natures-way' },
  'ناتشرز واى': { brand: 'نيتشرز واي', brandEn: 'Nature’s Way', slug: 'natures-way' },
  'ناتشرز انسر': { brand: 'ناتشرز انسر', brandEn: 'Nature’s Answer', slug: 'natures-answer' },
  'ناتشرز تروث': { brand: 'ناتشرز تروث', brandEn: 'Nature’s Truth', slug: 'natures-truth' },
  'ناتشرز تروث ': { brand: 'ناتشرز تروث', brandEn: 'Nature’s Truth', slug: 'natures-truth' },
  'ناتشرز تروث‏': { brand: 'ناتشرز تروث', brandEn: 'Nature’s Truth', slug: 'natures-truth' },
  'ناتشورال': { brand: 'ناتشورال', brandEn: 'Natural', slug: 'natural' },
  'كارلسون': { brand: 'كارلسون', brandEn: 'Carlson', slug: 'carlson' },
  'دكتور ميلاكسين': { brand: 'دكتور ميلاكسين', brandEn: 'Dr. Melaxin', slug: 'dr-melaxin' },
  'جمالك': { brand: 'جمالك', brandEn: 'Jamalik', slug: 'jamalik' },
  'سينتري 21': { brand: 'سينتري 21', brandEn: 'Century 21', slug: 'century-21' },
  'سينتري': { brand: 'سينتري 21', brandEn: 'Century 21', slug: 'century-21' },
  'سكين فود': { brand: 'سكين فود', brandEn: 'Skin Food', slug: 'skin-food' },
  // Body / personal care
  'ريكسونا': { brand: 'ريكسونا', brandEn: 'Rexona', slug: 'rexona' },
  'سيكرت': { brand: 'سيكرت', brandEn: 'Secret', slug: 'secret' },
  'سيكريت': { brand: 'سيكرت', brandEn: 'Secret', slug: 'secret' },
  'اولد سبايس': { brand: 'أولد سبايس', brandEn: 'Old Spice', slug: 'old-spice' },
  'سودوكريم': { brand: 'سودوكريم', brandEn: 'Sudocrem', slug: 'sudocrem' },
  'بيبانثين': { brand: 'بيبانثين', brandEn: 'Bepanthen', slug: 'bepanthen' },
  'جليسوليد': { brand: 'جليسوليد', brandEn: 'Glysolid', slug: 'glysolid' },
  'نومبوزين': { brand: 'نومبوزين', brandEn: 'Numbuzin', slug: 'numbuzin' },
  'شيا مويستر': { brand: 'شيا مويستر', brandEn: 'SheaMoisture', slug: 'sheamoisture' },
  'شيا مويستشر': { brand: 'شيا مويستر', brandEn: 'SheaMoisture', slug: 'sheamoisture' },
  'شيا مويستر ': { brand: 'شيا مويستر', brandEn: 'SheaMoisture', slug: 'sheamoisture' },
  'شيا مويستر‏': { brand: 'شيا مويستر', brandEn: 'SheaMoisture', slug: 'sheamoisture' },
  'اريان': { brand: 'اريان', brandEn: 'Aryan', slug: 'aryan' },
  'فوريفر': { brand: 'فوريفر', brandEn: 'Forever', slug: 'forever' },
  // Devices / tools
  'براون': { brand: 'براون', brandEn: 'Braun', slug: 'braun' },
  'جولدن روز': { brand: 'جولدن روز', brandEn: 'Golden Rose', slug: 'golden-rose' },
  'كيو في': { brand: 'كيو في', brandEn: 'QV', slug: 'qv' },
  'كيوفي': { brand: 'كيو في', brandEn: 'QV', slug: 'qv' },
  'سول دي جانيرو': { brand: 'سول دي جانيرو', brandEn: 'Sol de Janeiro', slug: 'sol-de-janeiro' },
  'باث اند بودي': { brand: 'باث آند بودي وركس', brandEn: 'Bath & Body Works', slug: 'bath-body-works' },
  'باث اند بودير': { brand: 'باث آند بودي وركس', brandEn: 'Bath & Body Works', slug: 'bath-body-works' },
  'ماري اند ماي': { brand: 'ماري آند ماي', brandEn: 'Mary & May', slug: 'mary-may' },
  'ماري روث': { brand: 'ماري روث', brandEn: 'Mary Ruth', slug: 'mary-ruth' },
  'أكسيس واي': { brand: 'أكسيس واي', brandEn: 'Access W', slug: 'access-w' },
  'اكسيس واي': { brand: 'أكسيس واي', brandEn: 'Access W', slug: 'access-w' },
  'ام سوري فور ماي سكين': { brand: 'أم سوري فور ماي سكين', brandEn: 'I’m Sorry For My Skin', slug: 'im-sorry-for-my-skin' },
  'ام سوري فور ماي سكن': { brand: 'أم سوري فور ماي سكين', brandEn: 'I’m Sorry For My Skin', slug: 'im-sorry-for-my-skin' },
  'اي سي ام': { brand: 'آي سي إم', brandEn: 'ICM', slug: 'icm' },
  'أي سي إم': { brand: 'آي سي إم', brandEn: 'ICM', slug: 'icm' },
  'ايس سي ام': { brand: 'آي سي إم', brandEn: 'ICM', slug: 'icm' },
  'ديرما': { brand: 'ديرما', brandEn: 'Derma', slug: 'derma' },
  'فارماسيريز': { brand: 'فارماسيريز', brandEn: 'Pharmaceris', slug: 'pharmaceris' },
  'فارماسيرز': { brand: 'فارماسيريز', brandEn: 'Pharmaceris', slug: 'pharmaceris' },
  'فارم ستاي': { brand: 'فارم ستاي', brandEn: 'Farm Stay', slug: 'farm-stay' },
  'فارم ستي': { brand: 'فارم ستاي', brandEn: 'Farm Stay', slug: 'farm-stay' },
  'لي ستافورد': { brand: 'لي ستافورد', brandEn: 'Lee Stafford', slug: 'lee-stafford' },
  'سنتروم': { brand: 'سنتروم', brandEn: 'Centrum', slug: 'centrum' },
  'ميدي كوب': { brand: 'ميديكيوب', brandEn: 'Medicube', slug: 'medicube' },
  'ميديكيوب': { brand: 'ميديكيوب', brandEn: 'Medicube', slug: 'medicube' },
  'ميديكوب': { brand: 'ميديكيوب', brandEn: 'Medicube', slug: 'medicube' },
  'ميديكيوب': { brand: 'ميديكيوب', brandEn: 'Medicube', slug: 'medicube' },
  'دكتور الثيا': { brand: 'دكتور الثيا', brandEn: 'Doctor Althia', slug: 'doctor-althia' },
  'كاميل': { brand: 'كاميل', brandEn: 'Camel', slug: 'camel' },
  'بيتز': { brand: 'بيتز', brandEn: 'Pets', slug: 'pets' },
  'صانسيلك': { brand: 'صانسيلك', brandEn: 'Sunsilk', slug: 'sunsilk' },
  'اريال': { brand: 'اريال', brandEn: 'Ariel', slug: 'ariel' },
  'وادي النحل': { brand: 'وادي النحل', brandEn: 'Wadi Alnahl', slug: 'wadi-alnahl' },
  'مكس أب': { brand: 'ميكس أب', brandEn: 'Mix Up', slug: 'mix-up' },
  'ميكسا': { brand: 'ميكسا', brandEn: 'Mexa', slug: 'mexa' },
  'ميشا': { brand: 'ميشا', brandEn: 'Missha', slug: 'missha' },
  'ماري روث': { brand: 'ماري روث', brandEn: 'Mary Ruth', slug: 'mary-ruth' },
  'نيتروجينا': { brand: 'نيتروجينا', brandEn: 'Neutrogena', slug: 'neutrogena' },
  'نتروجينا': { brand: 'نيتروجينا', brandEn: 'Neutrogena', slug: 'neutrogena' },
  'نيتروجينا،': { brand: 'نيتروجينا', brandEn: 'Neutrogena', slug: 'neutrogena' },
  'سيتافيل': { brand: 'سيتافيل', brandEn: 'Cetaphil', slug: 'cetaphil' },
  'بيكسي': { brand: 'بيكسي', brandEn: 'Pixi', slug: 'pixi' },
  'ذا اورديناري': { brand: 'ذا اورديناري', brandEn: 'The Ordinary', slug: 'the-ordinary' },
  'ذاورديناري': { brand: 'ذا اورديناري', brandEn: 'The Ordinary', slug: 'the-ordinary' },
  'ذا بالم': { brand: 'ذا بالم', brandEn: 'The Balm', slug: 'the-balm' },
  'سكنسومنيا': { brand: 'سكنسومنيا', brandEn: 'SkinSoMnia', slug: 'skinsomnia' },
  'فيو بلس': { brand: 'فيو بلس', brandEn: 'View Plus', slug: 'view-plus' },
  'نيو بلس': { brand: 'نيو بلس', brandEn: 'New Plus', slug: 'new-plus' },
  'ايكوال بيري': { brand: 'ايكوال بيري', brandEn: 'Equal Berry', slug: 'equal-berry' },
  'ايموفورم': { brand: 'ايموفورم', brandEn: 'Aimofrom', slug: 'aimofrom' },
  'ايزينتري': { brand: 'ايزينتري', brandEn: 'Escentri', slug: 'escentri' },
  'اي بي ناتشورالز': { brand: 'اي بي ناتشورالز', brandEn: 'AP Naturals', slug: 'ap-naturals' },
  'ايه بي ناتشورالز': { brand: 'اي بي ناتشورالز', brandEn: 'AP Naturals', slug: 'ap-naturals' },
  'ديرم أكتيف': { brand: 'ديرم أكتيف', brandEn: 'Derm Active', slug: 'derm-active' },
  'نيوتريديرم': { brand: 'نيوتريديرم', brandEn: 'NeutriDerm', slug: 'neutriderm' },
  'فيفيسكال': { brand: 'فيفيسكال', brandEn: 'Viviscal', slug: 'viviscal' },
  'اوبتيمال': { brand: 'اوبتيمال', brandEn: 'Optimal', slug: 'optimal' },
  'ارجفيت': { brand: 'ارجفيت', brandEn: 'Argavit', slug: 'argavit' },
  'بيوكسين': { brand: 'بيوكسين', brandEn: 'BioXin', slug: 'bioxin' },
  'فاشكول': { brand: 'فاشكول', brandEn: 'Vashkul', slug: 'vashkul' },
  'توكوبو': { brand: 'توكوبو', brandEn: 'Tokobo', slug: 'tokobo' },
  'افريكاز بست': { brand: 'افريكاز بست', brandEn: 'Africas Best', slug: 'africas-best' },
  'كانتو': { brand: 'كانتو', brandEn: 'Cantu', slug: 'cantu' },
  'لاكمي': { brand: 'لاكمي', brandEn: 'Lakmé', slug: 'lakme' },
  'بيوريتو': { brand: 'بيوريتو', brandEn: 'Puretto', slug: 'puretto' },
  'بيبير منتس': { brand: 'بيبير منتس', brandEn: 'Pepper & Mints', slug: 'pepper-mints' },
  'بيبير منتسل': { brand: 'بيبير منتس', brandEn: 'Pepper & Mints', slug: 'pepper-mints' },
  'كرست': { brand: 'كرست', brandEn: 'Crest', slug: 'crest' },
  'كريم كاب': { brand: 'كريم كاب', brandEn: 'Cream Cap', slug: 'cream-cap' },
  'بيبي ليس': { brand: 'بيبي ليس', brandEn: 'Babyliss', slug: 'babyliss' },
  'روز أروما': { brand: 'روز أروما', brandEn: 'Rose Aroma', slug: 'rose-aroma' },
  'تنج برش': { brand: 'تنج برش', brandEn: 'Tongue Brush', slug: 'tongue-brush' },
  'تانج برش': { brand: 'تنج برش', brandEn: 'Tongue Brush', slug: 'tongue-brush' },
  'ايكو تولز': { brand: 'ايكو تولز', brandEn: 'EcoTools', slug: 'ecotools' },
  'ريل تكنيك': { brand: 'ريل تكنيك', brandEn: 'Real Techniques', slug: 'real-techniques' },
  'ريال تكنك': { brand: 'ريل تكنيك', brandEn: 'Real Techniques', slug: 'real-techniques' },
  'ليدي سبيد ستيك': { brand: 'ليدي سبيد ستيك', brandEn: 'Lady Speed Stick', slug: 'lady-speed-stick' },
  'ميبو': { brand: 'ميبو', brandEn: 'MEBO', slug: 'mebo' },
  'سودوكريم': { brand: 'سودوكريم', brandEn: 'Sudocrem', slug: 'sudocrem' },
  'كيربروست': { brand: 'كيربروست', brandEn: 'Kerastase', slug: 'kerastase' },
  'ديبيوردينت': { brand: 'ديبيوردينت', brandEn: 'Dabur Dent', slug: 'dabur-dent' },
  'فنياني': { brand: 'فنياني', brandEn: 'Finiani', slug: 'finiani' },
  'ايلدن': { brand: 'ايلدن', brandEn: 'Elden', slug: 'elden' },
  'سيسديرما': { brand: 'سيسديرما', brandEn: 'Sesderma', slug: 'sesderma' },
  'مارفيس': { brand: 'مارفيس', brandEn: 'Marvis', slug: 'marvis' },
  'كامبلي': { brand: 'كامبلي', brandEn: 'Kampli', slug: 'kampli' },
  'فيتابير': { brand: 'فيتابير', brandEn: 'Vitabears', slug: 'vitabears' },
  'مايلد باي ناتشور ': { brand: 'مايلد باي ناتشور', brandEn: 'Mild By Nature', slug: 'mild-by-nature' },
  'مايلد باي ناتشور': { brand: 'مايلد باي ناتشور', brandEn: 'Mild By Nature', slug: 'mild-by-nature' },
  'مايلد باي ناتشور‏': { brand: 'مايلد باي ناتشور', brandEn: 'Mild By Nature', slug: 'mild-by-nature' },
  'نيوسيل': { brand: 'نيوسيل', brandEn: 'Neocell', slug: 'neocell' },
  'ايفلين': { brand: 'ايفلين', brandEn: 'Eveline', slug: 'eveline' },
  'إيفلين': { brand: 'ايفلين', brandEn: 'Eveline', slug: 'eveline' },
  'ميديكيوب': { brand: 'ميديكيوب', brandEn: 'Medicube', slug: 'medicube' },
  'ايسكينول': { brand: 'ايسكينول', brandEn: 'SkinOwl', slug: 'skinowl' },
  'اوفرا': { brand: 'اوفرا', brandEn: 'Ofera', slug: 'ofera' },
  'سارا': { brand: 'سارا', brandEn: 'Sara', slug: 'sara' },
  'انوار': { brand: 'انوار', brandEn: 'Anwar', slug: 'anwar' },
  'هيماني': { brand: 'هيماني', brandEn: 'Hemani', slug: 'hemani' },
  'الماس': { brand: 'الماس', brandEn: 'Almas', slug: 'almas' },
  'امبير': { brand: 'امبير', brandEn: 'Amber', slug: 'amber' },
  'فير ليدي': { brand: 'فير ليدي', brandEn: 'Fair Lady', slug: 'fair-lady' },
  'من فير ليدي': { brand: 'فير ليدي', brandEn: 'Fair Lady', slug: 'fair-lady' },
  'توفيسد': { brand: 'توفيسد', brandEn: 'Tofisd', slug: 'tofisd' },
  'الخزامى': { brand: 'الخزامى', brandEn: 'Lavender', slug: 'lavender' },
  'كريستين': { brand: 'كريستين', brandEn: 'Christine', slug: 'christine' },
  'ميلي': { brand: 'ميلي', brandEn: 'Milay', slug: 'milay' },
  'دي لا كروز': { brand: 'دي لا كروز', brandEn: 'De La Cruz', slug: 'de-la-cruz' },
  'تري هت': { brand: 'تري هت', brandEn: 'Tree Hut', slug: 'tree-hut' },
  'سول دي جانيرو': { brand: 'سول دي جانيرو', brandEn: 'Sol de Janeiro', slug: 'sol-de-janeiro' },
  'فيلورجا': { brand: 'فيلورجا', brandEn: 'Filorga', slug: 'filorga' },
  'امبريوليس': { brand: 'امبريوليس', brandEn: 'Embryolisse', slug: 'embryolisse' },
  'اريان': { brand: 'اريان', brandEn: 'Aryan', slug: 'aryan' },
  'فوكس': { brand: 'فوكس', brandEn: 'Fox', slug: 'fox' },
  'بيجي': { brand: 'بيجي', brandEn: 'Pegee', slug: 'pegee' },
  'بريتي': { brand: 'بريتي', brandEn: 'Pretty', slug: 'pretty' },
  'ليتل بيبي': { brand: 'ليتل بيبي', brandEn: 'Little Baby', slug: 'little-baby' },
  'مومز باث': { brand: 'مومز باث', brandEn: 'Mom’s Bath', slug: 'moms-bath' },
  'افينو': { brand: 'أفينو', brandEn: 'Aveeno', slug: 'aveeno' },
  'نوبيان هيريتج': { brand: 'نوبيان هيريتج', brandEn: 'Nubian Heritage', slug: 'nubian-heritage' },
  'سكينورين': { brand: 'سكينورين', brandEn: 'Skinoren', slug: 'skinoren' },
  'بانثينول بلس': { brand: 'بانثينول بلس', brandEn: 'Panthenol Plus', slug: 'panthenol-plus' },
  'باولاز تشويس': { brand: 'باولاز تشويس', brandEn: 'Paula’s Choice', slug: 'paulas-choice' },
  'باولاز': { brand: 'باولاز تشويس', brandEn: 'Paula’s Choice', slug: 'paulas-choice' },
  'ايليشاكوي': { brand: 'ايليشاكوي', brandEn: 'Elishacoy', slug: 'elishacoy' },
  'بيورسكين': { brand: 'بيورسكين', brandEn: 'Pure Skin', slug: 'pure-skin' },
  'أوركس': { brand: 'أوركس', brandEn: 'Orex', slug: 'orex' },
  'فاني كريم': { brand: 'فاني كريم', brandEn: 'Vanis Cream', slug: 'vanis-cream' },
  'ذا فيس شوب': { brand: 'ذا فيس شوب', brandEn: 'The Face Shop', slug: 'the-face-shop' },
  'نيتشر ريببلك': { brand: 'نيتشر ريببلك', brandEn: 'Nature Republic', slug: 'nature-republic' },
  'ناتشر ريببلك': { brand: 'نيتشر ريببلك', brandEn: 'Nature Republic', slug: 'nature-republic' },
  'كيلز': { brand: 'كيلز', brandEn: 'Kiehl’s', slug: 'kiehls' },
  'فلامينجو': { brand: 'فلامينجو', brandEn: 'Flamingo', slug: 'flamingo' },
  'ايتود هاوس': { brand: 'ايتود هاوس', brandEn: 'Etude House', slug: 'etude-house' },
  'سام باي مي': { brand: 'سوم باي مي', brandEn: 'Some By Mi', slug: 'some-by-mi' },
  'ستيكس': { brand: 'ستيكس', brandEn: 'Stickes', slug: 'stickes' },
  'غودال': { brand: 'غودال', brandEn: 'Godall', slug: 'godall' },
  'جي كوزمك': { brand: 'جي كوزمك', brandEn: 'G Cosmetic', slug: 'g-cosmetic' },
  'ميكسون': { brand: 'ميكسون', brandEn: 'MixOn', slug: 'mixon' },
  'شيك انتيوشن': { brand: 'شيك انتيوشن', brandEn: 'Shik Intuition', slug: 'shik-intuition' },
  'ماشينزا': { brand: 'ماشينزا', brandEn: 'Mashenza', slug: 'mashenza' },
  'كيمفور': { brand: 'كيمفور', brandEn: 'Kimphur', slug: 'kimphur' },
  'ماركة غير محددة': { brand: 'ماركة غير محددة', brandEn: 'Generic', slug: 'generic' },
  'يوني برو': { brand: 'يوني برو', brandEn: 'Uni Pro', slug: 'uni-pro' },
  'نيو بلس': { brand: 'نيو بلس', brandEn: 'New Plus', slug: 'new-plus' },
  'بروتوكول': { brand: 'بروتوكول', brandEn: 'Protocol', slug: 'protocol' },
  'سكين 1004': { brand: 'سكين 1004', brandEn: 'SKIN1004', slug: 'skin1004' },
};

/** Normalize a raw brand string to canonical {brand, brandEn, slug}. */
export function normalizeBrand(raw) {
  if (!raw) return { brand: '', brandEn: '', slug: '' };
  let key = raw.trim().replace(/^[\u064B-\u065F\s]+/, '').replace(/\s+$/, '');
  // strip leading "من " if present
  key = key.replace(/^من\s+/, '');
  if (MAP[key]) return { ...MAP[key] };
  // try without trailing commas
  const stripped = key.replace(/[،,]+$/g, '').trim();
  if (MAP[stripped]) return { ...MAP[stripped] };
  // fallback: keep as-is, build slug
  const slug = key.replace(/\s+/g, '-').replace(/[^\u0600-\u06FFa-zA-Z0-9-]/g, '').toLowerCase() || 'brand';
  return { brand: key, brandEn: key, slug };
}

export default { normalizeBrand, MAP };
