export {
  products,
  categories,
  sectionCategories,
  sectionCategoriesMap,
  getProductBySlug,
  getProductsByCategory,
  getCategoryBySlug,
  getFeaturedProducts,
  getNewArrivals,
  getBestSellers,
  getDoctorRecommended,
  getRelatedProducts,
  searchProducts,
  routines,
} from "@/src/data/products";