import type { Product } from "../../src/types/product";

/** Deterministic default Product for test fixtures. */
export function makeProduct(overrides: Partial<Product> = {}): Product {
  return {
    id: "test-1",
    slug: "test-1",
    sku: "TEST-1",
    brand: "TestBrand",
    brandAr: "TestBrand",
    name: { ar: "كريم مرطب للوجه 50 مل", en: "Test Moisturizer 50ml" },
    category: "Moisturizers",
    categoryAr: "مرطبات",
    categorySlug: "moisturizers",
    description: { ar: "", en: "" },
    pricing: { price: 5000, currency: "YER", originalPrice: 6000 },
    discount: 1000,
    gallery: ["/img/1.jpg"],
    images: ["/img/1.jpg"],
    ingredients: { ar: ["جلسرين"], en: ["glycerin"] },
    usageInstructions: { ar: "يوضع على البشرة النظيفة.", en: "Apply to clean skin." },
    howToUse: ["Apply to clean skin."],
    howToUseAr: ["يوضع على البشرة النظيفة."],
    skinTypes: ["dry"],
    suitableFor: ["dry"],
    skinConcerns: ["dryness"],
    benefits: { ar: ["يرطب البشرة الجافة"], en: ["hydrates dry skin"] },
    stock: 10,
    inStock: true,
    stockQuantity: 10,
    rating: 4.5,
    reviewCount: 5,
    featured: false,
    isFeatured: false,
    new: false,
    isNew: false,
    isBestSeller: false,
    isDoctorRecommended: false,
    tags: [],
    seoMetadata: {
      title: { ar: "كريم مرطب", en: "Moisturizer" },
      description: { ar: "", en: "" },
      keywords: [],
    },
    sizeLabel: "50 مل",
    status: "published",
    ...overrides,
  };
}